### ISSUE TITLE
Missing argument in assistant.py in call to audio_helpers.ConversationStream

### ISSUE THREAD

**Issue by ipio** [warchildmd/google-assistant-hotword-raspi#1]
It should be corrected from this:

        self.conversation_stream = audio_helpers.ConversationStream(
            source=self.audio_source,
            sink=self.audio_sink,
            iter_size=self.audio_iter_size,
        )

to this:

        self.conversation_stream = audio_helpers.ConversationStream(
            source=self.audio_source,
            sink=self.audio_sink,
            iter_size=self.audio_iter_size,
            sample_width=self.audio_sample_width
        )

**Comment by phdemartin** [comment]
Exactly, I've edited the assistant.py acordingly and the error is gone

**Comment by warchildmd** [comment]
Solved #4
