### ISSUE TITLE
Sudo command not recognized ?

### ISSUE THREAD

**Issue by Quite-brokeN** [warchildmd/google-assistant-hotword-raspi#14]
when i try to execute the command "sudo apt-get install portaudio19-dev libffi-dev libssl-dev"
it says Sudo command not recognized as an internal or external command,
![image](https://user-images.githubusercontent.com/35708562/35247520-c880e98a-ffdb-11e7-9867-b2c263dcb34f.png)
 any help ?

**Comment by warchildmd** [comment]
Hi @YahiyaGaming,

It seems you are using Windows OS, the commands used in the README are specific to Linux (Debian/Ubuntu).

For Windows you can just download and install https://anaconda.org/anaconda/python
